name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "natthapong41@gmail.com"
        git config --global user.name "babe124578"
        git remote set-url origin https://c44d1d0475e69892a9db0e6c31481e0d40b6c1f0@github.com/babe124578/social-dashboard.git
        npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
